### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wongsyrone** [wongsyrone/shadowsocks-windows#1]
- [ ] add i18n of in/out traffic

**Comment by ProfessorX** [comment]
老板，你新发布的这个14936的补丁是源码啊，有没有直接Build好了的exe文件啊。。。Surface烂电脑没有装C#啊。

**Comment by wongsyrone** [comment]
还不确保一定能修好，https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows/build/1.0.123/job/3kr7xo0ey89vv5gn/artifacts

**Comment by ProfessorX** [comment]
换了新版本之后，我把启用系统代理关了，在IE的连接里面设置的（其实WIndows Setting里面那个跟IE的是同步的），设置好localhost跟端口之后就没问题了。

具体是什么问题不清楚，照例把log给你贴上来。

2016-10-05 11:40:49] Shadowsocks started
[2016-10-05 11:52:30] Auto (s0.*******.com:47) timed out
[2016-10-05 11:52:34] Auto (s0.*******.com:4 timed out
[2016-10-05 11:52:34] System.Reflection.TargetInvocationException: An exception occurred during the operation, making the result invalid.  Check InnerException for exception details. ---> System.Net.WebException: The underlying connection was closed: An unexpected error occurred on a send. ---> System.IO.IOException: Authentication failed because the remote party has closed the transport stream.
   at System.Net.TlsStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.PooledStream.EndWrite(IAsyncResult asyncResult)
   at System.Net.ConnectStream.WriteHeadersCallback(IAsyncResult ar)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
   --- End of inner exception stack trace ---
   at System.ComponentModel.AsyncCompletedEventArgs.RaiseExceptionIfNecessary()
   at Shadowsocks.Controller.UpdateChecker.http_DownloadStringCompleted(Object sender, DownloadStringCompletedEventArgs e)
[2016-10-05 11:53:08] Shadowsocks started
[2016-10-05 11:57:27] Shadowsocks started
[2016-10-05 11:57:31] Shadowsocks started
[2016-10-05 11:57:52] Shadowsocks started

**Comment by wongsyrone** [comment]
也就是说现在14936也能正常控制了？

**Comment by brian763** [comment]
3.3.2在win server 2016下无法打开（瞬间闪退），已授予管理员权限，而3.3.1完美运行。

**Comment by wongsyrone** [comment]
提供日志或者错误截图

**Comment by brian763** [comment]
日志名称:          Application
来源:            Microsoft-Windows-Immersive-Shell
日期:            2016/10/7 10:10:57
事件 ID:         5973
任务类别:          (5973)
级别:            错误
关键字:           
用户:            WIN-B42RTPMQL8S\Administrator
计算机:           WIN-B42RTPMQL8S
描述:
激活应用 Microsoft.Windows.Apprep.ChxApp_cw5n1h2txyewy:App.AppXc99k5qnnsvxj5szemm7fp3g7y08we5vm.mca 失败，错误: 内置管理员无法激活此应用。 请查看 Microsoft-Windows-TWinUI/运行日志以了解其他信息。
事件 Xml:
<Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
  <System>
    <Provider Name="Microsoft-Windows-Immersive-Shell" Guid="{315A8872-923E-4EA2-9889-33CD4754BF64}" />
    <EventID>5973</EventID>
    <Version>0</Version>
    <Level>2</Level>
    <Task>5973</Task>
    <Opcode>0</Opcode>
    <Keywords>0x2000000000000000</Keywords>
    <TimeCreated SystemTime="2016-10-07T02:10:57.921088900Z" />
    <EventRecordID>1475</EventRecordID>
    <Correlation ActivityID="{4BD56110-1F7A-0002-DE4F-D94B7A1FD201}" />
    <Execution ProcessID="3444" ThreadID="7140" />
    <Channel>Application</Channel>
    <Computer>WIN-B42RTPMQL8S</Computer>
    <Security UserID="S-1-5-21-4003860360-3310848217-761983703-500" />
  </System>
  <EventData>
    <Data Name="AppId">Microsoft.Windows.Apprep.ChxApp_cw5n1h2txyewy:App.AppXc99k5qnnsvxj5szemm7fp3g7y08we5vm.mca</Data>
    <Data Name="ErrorCode">-2144927149</Data>
  </EventData>
</Event>

**Comment by wongsyrone** [comment]
Don't use internal Administrator, try another user with administrative permission or try https://ci.appveyor.com/project/wongsyrone/shadowsocks-windows-0cn3i/build/1.0.93/job/e5fkmkj78bqqqexf/artifacts
